pipeline {
    agent any

    environment {
        // .env 파일의 환경 변수를 빌드 환경으로 설정
        DOT_DEV = credentials('osondoson-backend-env')
        ECR_REPO = '014276069644.dkr.ecr.ap-northeast-2.amazonaws.com/osondoson-backend'

        AWS_CREDENTIAL_ID = 'ecr-user'
        REGION = 'ap-northeast-2'
    }

    stages {
        stage('Checkout') {
            steps {
                deleteDir() // 이전에 가져온 소스 코드를 모두 삭제
                checkout scm
                sh 'git checkout develop'
            }
        }

        stage('Append .env file') {
            steps {
                withCredentials([file(credentialsId: 'osondoson-backend-env', variable: 'DOTENV_FILE')]) {
                    sh "cat ${DOTENV_FILE} >> .env"
                }
            }
        }

        stage('Docker build') {
            steps {
                sh "docker build -t ${ECR_REPO}:latest ."
            }
        }

        stage("Push to ECR") {
            steps {
                script {
                    // docker push
                    docker.withRegistry("https://${ECR_REPO}", "ecr:${REGION}:${AWS_CREDENTIAL_ID}") {
                        docker.image("${ECR_REPO}:latest").push()
                    }
                }
            }
        }
    }
}
